# Generated by Django 3.2.9 on 2021-11-06 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_movies_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='actors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('age', models.IntegerField(null=True)),
                ('nationality', models.CharField(max_length=255, null=True)),
                ('known_for', models.CharField(max_length=255, null=True)),
                ('profile_pic', models.ImageField(null=True, upload_to='actors/images')),
            ],
        ),
        migrations.AddField(
            model_name='movies',
            name='poster',
            field=models.ImageField(null=True, upload_to='movies/images'),
        ),
        migrations.AddField(
            model_name='movies',
            name='video',
            field=models.FileField(null=True, upload_to='movies/videos'),
        ),
    ]
