# Generated by Django 3.2.9 on 2021-11-06 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20211106_0119'),
    ]

    operations = [
        migrations.CreateModel(
            name='cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('age', models.IntegerField(null=True)),
                ('job', models.CharField(default='Actor', max_length=255)),
                ('nationality', models.CharField(max_length=255, null=True)),
                ('known_for', models.CharField(max_length=255, null=True)),
                ('profile_pic', models.ImageField(null=True, upload_to='actors/images')),
            ],
        ),
        migrations.DeleteModel(
            name='actors',
        ),
    ]
