# Generated by Django 3.2.9 on 2021-11-06 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20211106_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='actors/images'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='movies/images'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='movies/videos'),
        ),
    ]
