# Generated by Django 3.2.9 on 2021-11-09 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20211108_2302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cast',
            options={'ordering': ['-age'], 'verbose_name_plural': 'Cast'},
        ),
        migrations.AlterModelOptions(
            name='movies',
            options={'ordering': ['imdp_rate'], 'verbose_name_plural': 'Movies'},
        ),
        migrations.AddField(
            model_name='movies',
            name='cast',
            field=models.ManyToManyField(to='movies.cast'),
        ),
        migrations.AlterField(
            model_name='cast',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='movies/actors/images'),
        ),
    ]
