# Generated by Django 3.2.9 on 2021-11-09 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0007_auto_20211109_0155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cast',
            options={'ordering': ['age'], 'verbose_name_plural': 'Cast'},
        ),
        migrations.AlterModelOptions(
            name='movies',
            options={'ordering': ['-imdp_rate'], 'verbose_name_plural': 'Movies'},
        ),
        migrations.AlterField(
            model_name='cast',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='movies/cast/images'),
        ),
        migrations.CreateModel(
            name='movies_comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250)),
                ('attachment', models.ImageField(blank=True, null=True, upload_to='movies/attachment/movies')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='cast_comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250)),
                ('attachment', models.ImageField(blank=True, null=True, upload_to='movies/attachment/cast')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
