# Generated by Django 3.2.9 on 2021-11-09 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0008_auto_20211109_0210'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('attachment', models.ImageField(blank=True, null=True, upload_to='movies/attachment/movies')),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.movies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='movies_comments',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='movies_comments',
            name='user',
        ),
        migrations.DeleteModel(
            name='cast_comments',
        ),
        migrations.DeleteModel(
            name='movies_comments',
        ),
    ]
