# Generated by Django 3.2.9 on 2021-11-09 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0009_auto_20211109_0223'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comments',
            new_name='movies_comment',
        ),
        migrations.CreateModel(
            name='cast_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('attachment', models.ImageField(blank=True, null=True, upload_to='movies/attachment/cast')),
                ('cast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.cast')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
