# Generated by Django 3.2.9 on 2021-11-09 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_auto_20211109_0224'),
    ]

    operations = [
        migrations.CreateModel(
            name='cast_ssn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssn', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='movie_serial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=50)),
            ],
        ),
    ]
