# Generated by Django 3.2.9 on 2021-11-09 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_auto_20211109_0246'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='movie_serial',
            new_name='movies_serial',
        ),
    ]
