# Generated by Django 3.2.9 on 2021-11-09 18:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_rename_movie_serial_movies_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast_comment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='movies_comment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='movies',
            name='cast',
            field=models.ManyToManyField(blank=True, null=True, to='movies.cast'),
        ),
    ]
