# Generated by Django 3.2.9 on 2021-11-09 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_auto_20211109_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='like',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
